import About from "../src/components/About/About";
import ContactUs from "../src/components/ContactUs/ContactUs";
import Galery from "../src/components/Galery/Galery";
import Head from "next/head";
import Layout from "../src/components/Layout/Layout";
import Questions from "../src/components/Questions/Questions";
import Review from "../src/components/Review/Review";
import Technologies from "../src/components/Technologies/Technologies";
import Steps from "../src/components/Steps/Steps";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta http-equiv='Cache-Control' content='no-cache'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <About />
        <Technologies />
        <Steps />
        <Review />
        <Galery />
        <Questions />
        <ContactUs />
      </Layout>
    </>
  );
}
