import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import classes from "../styles/Home.module.css";
import Heading from "../components/UI/Heading/Heading";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Heading size='1'>H1/150px</Heading>
        <Heading size='2'>H2/72px</Heading>
        <Heading size='3'>H3/32px</Heading>
        <Heading size='4'>H3/24px</Heading>
        <p>P1/16px</p>
        <p>P2/14px</p>
      </main>
    </>
  );
}
